//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.20 at 12:33:55 PM EDT 
//


package com.kaizensundays.fusion.quickfix.fix44;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}field"/>
 *           &lt;element ref="{}group"/>
 *         &lt;/choice>
 *         &lt;element ref="{}component" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "fieldOrGroup",
        "component"
})
@XmlRootElement(name = "component")
public class Component {

    @XmlElements({
            @XmlElement(name = "field", type = Field.class),
            @XmlElement(name = "group", type = Group.class)
    })
    protected List<Object> fieldOrGroup;
    protected Component component;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlAttribute(name = "required")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String required;

    /**
     * Gets the value of the fieldOrGroup property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldOrGroup property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldOrGroup().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * {@link Group }
     */
    public List<Object> getFieldOrGroup() {
        if (fieldOrGroup == null) {
            fieldOrGroup = new ArrayList<Object>();
        }
        return this.fieldOrGroup;
    }

    /**
     * Gets the value of the component property.
     *
     * @return possible object is
     * {@link Component }
     */
    public Component getComponent() {
        return component;
    }

    /**
     * Sets the value of the component property.
     *
     * @param value allowed object is
     *              {@link Component }
     */
    public void setComponent(Component value) {
        this.component = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the required property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRequired(String value) {
        this.required = value;
    }

}
