//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.20 at 12:33:55 PM EDT 
//


package com.kaizensundays.fusion.quickfix.fix44;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}header"/>
 *         &lt;element ref="{}trailer"/>
 *         &lt;element ref="{}messages"/>
 *         &lt;element ref="{}components"/>
 *         &lt;element ref="{}fields"/>
 *       &lt;/sequence>
 *       &lt;attribute name="major" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="minor" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "header",
        "trailer",
        "messages",
        "components",
        "fields"
})
@XmlRootElement(name = "fix")
public class Fix {

    @XmlElement(required = true)
    protected Header header;
    @XmlElement(required = true)
    protected Trailer trailer;
    @XmlElement(required = true)
    protected Messages messages;
    @XmlElement(required = true)
    protected Components components;
    @XmlElement(required = true)
    protected Fields fields;
    @XmlAttribute(name = "major", required = true)
    protected BigInteger major;
    @XmlAttribute(name = "minor", required = true)
    protected BigInteger minor;

    /**
     * Gets the value of the header property.
     *
     * @return possible object is
     * {@link Header }
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     *
     * @param value allowed object is
     *              {@link Header }
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the trailer property.
     *
     * @return possible object is
     * {@link Trailer }
     */
    public Trailer getTrailer() {
        return trailer;
    }

    /**
     * Sets the value of the trailer property.
     *
     * @param value allowed object is
     *              {@link Trailer }
     */
    public void setTrailer(Trailer value) {
        this.trailer = value;
    }

    /**
     * Gets the value of the messages property.
     *
     * @return possible object is
     * {@link Messages }
     */
    public Messages getMessages() {
        return messages;
    }

    /**
     * Sets the value of the messages property.
     *
     * @param value allowed object is
     *              {@link Messages }
     */
    public void setMessages(Messages value) {
        this.messages = value;
    }

    /**
     * Gets the value of the components property.
     *
     * @return possible object is
     * {@link Components }
     */
    public Components getComponents() {
        return components;
    }

    /**
     * Sets the value of the components property.
     *
     * @param value allowed object is
     *              {@link Components }
     */
    public void setComponents(Components value) {
        this.components = value;
    }

    /**
     * Gets the value of the fields property.
     *
     * @return possible object is
     * {@link Fields }
     */
    public Fields getFields() {
        return fields;
    }

    /**
     * Sets the value of the fields property.
     *
     * @param value allowed object is
     *              {@link Fields }
     */
    public void setFields(Fields value) {
        this.fields = value;
    }

    /**
     * Gets the value of the major property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getMajor() {
        return major;
    }

    /**
     * Sets the value of the major property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setMajor(BigInteger value) {
        this.major = value;
    }

    /**
     * Gets the value of the minor property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getMinor() {
        return minor;
    }

    /**
     * Sets the value of the minor property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setMinor(BigInteger value) {
        this.minor = value;
    }

}
